server:
#  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:~/h2/blog-app
    username: sa
    password:
    driverClassName: org.h2.Driver
    console.enabled: true
  h2:
    console.enabled: true
#  hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

